project:
  type: book
  output-dir: _book
  execute-dir: project

book:
  title: Open Science Indicator Handbook
  reader-mode: true

  site-url: https://pathos-project.eu/
  repo-url: https://github.com/PathOS-project/indicator_handbook/
  repo-branch: main
  repo-actions: [edit, issue]

  chapters:
    - index.qmd

    # - causal_intro/article/intro-causality.qmd Skip causal intro for now

    - part: Open Science
      chapters:
        - indicator_templates/quarto/1_open_science/APC_costs.qmd
        - indicator_templates/quarto/1_open_science/availability_data_repositories.qmd
        - indicator_templates/quarto/1_open_science/availability_preprint_repositories.qmd
        - indicator_templates/quarto/1_open_science/availability_publication_repositories.qmd
        - indicator_templates/quarto/1_open_science/citizens_science.qmd
        - indicator_templates/quarto/1_open_science/deposition_open_metadata.qmd
        - indicator_templates/quarto/1_open_science/evaluation_open_science_in_research_assessment.qmd
        - indicator_templates/quarto/1_open_science/open_access_journals.qmd
        - indicator_templates/quarto/1_open_science/open_access_uptake.qmd
        - indicator_templates/quarto/1_open_science/open_science_training_facilities.qmd
        - indicator_templates/quarto/1_open_science/prevalence_national_open_science_policies.qmd
        - indicator_templates/quarto/1_open_science/prevalence_open_fair_data_practices.qmd
        - indicator_templates/quarto/1_open_science/prevalence_open_method_practices.qmd
        - indicator_templates/quarto/1_open_science/prevalence_open_peer_review.qmd
        - indicator_templates/quarto/1_open_science/prevalence_open_science_funding_policies.qmd
        - indicator_templates/quarto/1_open_science/prevalence_open_science_support.qmd
        - indicator_templates/quarto/1_open_science/prevalence_preprinting.qmd
        - indicator_templates/quarto/1_open_science/prevalence_replication_studies.qmd
        - indicator_templates/quarto/1_open_science/transformative_publishing_agreements.qmd

    - part: Academic Impact

    - part: Societal Impact

    - part: Economic Impact

    - part: Reproducibility
      chapters:
        - 'indicator_templates/quarto/5_reproducibility/consistency_in_reported_numbers.qmd'
        - 'indicator_templates/quarto/5_reproducibility/impact_of_open_code_in_research.qmd'
        - 'indicator_templates/quarto/5_reproducibility/impact_of_open_data_in_research.qmd'
        - 'indicator_templates/quarto/5_reproducibility/inclusion_in_systematic_reviews_or_meta-analyses.qmd'
        - 'indicator_templates/quarto/5_reproducibility/indicator_template.qmd'
        - 'indicator_templates/quarto/5_reproducibility/levels_of_replication_found.qmd'
        - 'indicator_templates/quarto/5_reproducibility/polarity_of_publications.qmd'
        - 'indicator_templates/quarto/5_reproducibility/reuse_of_code_in_research.qmd'
        - 'indicator_templates/quarto/5_reproducibility/reuse_of_data_in_research.qmd'
        - 'indicator_templates/quarto/5_reproducibility/rigour_in_reporting.qmd'

format:
  html:
    theme:
      - cosmo
    code-link: true
    grid:
      sidebar-width: 350px

    author-meta: "V.A. Traag, etc..."
    callout-appearance: simple

  pdf:
    documentclass: report
    margin-left: 30mm
    margin-right: 30mm    

  docx:
    reference-doc: template/template.docx

editor: visual