on:
  push:
    branches: main
  pull_request:
    branches: main
  # to be able to trigger a manual build
  workflow_dispatch:

name: Render indicator handbook

jobs:

  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.PRIVATE_REPO }}

      - name: Setup quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render quarto project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html # If set, it will be equivalent to `quarto render --to html`

      - name: Upload rendered book as GHA artifact
        uses: actions/upload-artifact@v3
        with:
          name: indicators_handbook
          path: _book/
